In [1]:
import numpy as np

In [2]:
# 1. Create a NumPy array containing integers from 0 to 9.
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].
# Python list
my_list = [87,3,54,10,32]

# Convert list to NumPy array
arr = np.array(my_list)

print(arr)

[87  3 54 10 32]


In [5]:
# 3. Create a 2D array (3x3) with values ranging from 0 to 8.
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between
# 1 and 100, and print the shape and size.
# Create a 5x4 array with random integers between 1 and 100
arr = np.random.randint(1, 101, (5, 4))

print("Array:")
print(arr)

# Find shape
print("\nShape of array:")
print(arr.shape)

# Find size
print("\nSize of array:")
print(arr.size)

Array:
[[87 45 66 85]
 [12  1 34 76]
 [11  4 67 19]
 [94  9  5 62]
 [83 24 95 71]]

Shape of array:
(5, 4)

Size of array:
20


In [12]:
# 5. Create a 3x3 array of integers and access:
# Create a 3x3 array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Array:")
print(arr)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# a. Second element of the first row
print("\na. Second element of first row:")
print(arr[0, 1])

# b. Third column of the 2nd row
print("\nb. Third element of 2nd row:")
print(arr[1, 2])

# c. Subarray with first two rows and last two columns
print("\nc. Subarray:")
print(arr[:2, 1:])


a. Second element of first row:
2

b. Third element of 2nd row:
6

c. Subarray:
[[2 3]
 [5 6]]


In [14]:
# 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.
# Create a 1D array with 12 elements
arr = np.arange(1, 13)

print("1D Array:")
print(arr)

# Reshape into 3x4 2D array
arr_2d = arr.reshape(3, 4)

print("\n3x4 Reshaped Array:")
print(arr_2d)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# 7. Reshape a 3x3 matrix into a 1D array.
# Create a 3x3 matrix
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 array:")
print(arr)

# Reshape into 1D array
arr_1d = arr.reshape(9)

print("\nReshaped 1D array:")
print(arr_1d)

Original 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped 1D array:
[1 2 3 4 5 6 7 8 9]


In [16]:
# 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
# subtraction, multiplication, and division on them.
# Create two arrays of shape (2, 3)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

#addition
print("\nAddition:")
print(arr1 + arr2)

#subtraction
print("\nSubtraction:")
print(arr1 - arr2)

#multiplication
print("\nMultiplication:")
print(arr1 * arr2)

#division
print("\nDivision:")
print(arr1 / arr2)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Addition:
[[11 22 33]
 [44 55 66]]

Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Multiplication:
[[ 10  40  90]
 [160 250 360]]

Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [17]:
# 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a
# given array.
arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

# Sum of elements
print("\nSum:")
print(np.sum(arr))

# Mean (average)
print("\nMean:")
print(np.mean(arr))

# Standard deviation
print("\nStandard Deviation:")
print(np.std(arr))

Array:
[10 20 30 40 50]

Sum:
150

Mean:
30.0

Standard Deviation:
14.142135623730951


In [19]:
# 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
# the @ operator.
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Matrix multiplication using np.dot()
print("\nUsing np.dot():")
print(np.dot(A, B))

# Matrix multiplication using @ operator
print("\nUsing @ operator:")
print(A @ B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Using np.dot():
[[19 22]
 [43 50]]

Using @ operator:
[[19 22]
 [43 50]]


In [20]:
# 11. Find the transpose of matrix A and matrix B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Transpose of A
print("\nTranspose of A:")
print(A.T)

# Transpose of B
print("\nTranspose of B:")
print(B.T)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Transpose of A:
[[1 3]
 [2 4]]

Transpose of B:
[[5 7]
 [6 8]]


In [21]:
# 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the
# entire array.
arr = np.random.randint(1, 101, (4, 4))

print("Array:")
print(arr)

# Maximum value
print("\nMaximum value:")
print(np.max(arr))

# Minimum value
print("\nMinimum value:")
print(np.min(arr))

# Mean value
print("\nMean value:")
print(np.mean(arr))

Array:
[[ 7 47 55 79]
 [93 62 49 58]
 [ 4 88 85 95]
 [66 69 21 66]]

Maximum value:
95

Minimum value:
4

Mean value:
59.0


In [25]:
# 14. Find the row-wise and column-wise sums.
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

row_sums = np.sum(a, axis=1)
print('Row-wise sum :\n',row_sums)

col_sums = np.sum(a, axis=0)
print('Column-wise sum :\n',col_sums)

Row-wise sum :
 [ 6 15 24]
Column-wise sum :
 [12 15 18]


In [26]:
# 15. Generate an array of 10 random integers between 1 and 50.
arr = np.random.randint(1, 51, size=10)
print(arr)

[50 45 31 42 34 20 45 12 20 39]


In [27]:
# 16. Generate a 5x5 matrix of random floats between 0 and 1.
matrix = np.random.rand(5, 5)
print(matrix)

[[0.70887241 0.74478675 0.53556792 0.5348762  0.51243223]
 [0.18617002 0.94444614 0.89056129 0.42999536 0.92189441]
 [0.97501986 0.89315734 0.80777314 0.18087177 0.21529436]
 [0.99288178 0.69416376 0.91894656 0.50064037 0.10934924]
 [0.64468155 0.4148101  0.39621583 0.23341982 0.75131951]]
