In [1]:
import numpy as np

In [3]:
# 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.
matrix = np.arange(2, 14).reshape(4, 3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [18]:
# 2. Create array with 20 random integers from 1 to 50
arr = np.random.randint(1, 50, 20)

print("Original Array:")
print(arr)

# Replace odd numbers with -1
arr[arr % 2 != 0] = -1

print("\nModified Array:")
print(arr)

Original Array:
[20 30 45 39 31 35 33 26 16 47 28 33 49 47  1 19 12 24 13 16]

Modified Array:
[20 30 -1 -1 -1 -1 -1 26 16 -1 28 -1 -1 -1 -1 -1 12 24 -1 16]


In [20]:
# 3. Perform the following operations on an array of mobile phones prices 6999, 7500,
# 11999, 27899, 14999, 9999.
# a. Create a 1d-array of mobile phones prices

prices = np.array([6999, 7500, 11999, 27899, 14999, 9999])

print("Original Array:")
prices

Original Array:


array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [23]:
# b. Convert this array to float type
prices = prices.astype(float)

print("\nFloat Type Array:")
prices


Float Type Array:


array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

In [24]:
# c. Append a new mobile price
prices = np.append(prices, 13999)

print("\nAfter Appending 13999:")
prices


After Appending 13999:


array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

In [26]:
# d. Reverse the array
prices = prices[::-1]

print("\nReversed Array:")
prices


Reversed Array:


array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

In [28]:
# f. Sort in descending order
prices = np.sort(prices)[::-1]

print("\nSorted in Descending Order:")
prices


Sorted in Descending Order:


array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

In [29]:
# g. Average mobile phone price
average_price = np.mean(prices)

print("\nAverage Price:")
average_price


Average Price:


np.float64(15743.560000000001)